### ISSUE TITLE
Cannot see the deployment link its not working

### ISSUE THREAD

**Issue by Anu27n** [cxp-13/krypt_2024_latest#1]
https://krypt-2024-latest.vercel.app/ this link doesnt work some issue is there.

**Comment by lantianlaoli** [comment]
Can you share more info about the issue?

**Comment by Anu27n** [comment]
<img width="957" alt="image" src="https://github.com/user-attachments/assets/a644686e-5108-4425-81db-3055b8f23883" />
@cxp-13 blank page coming after clicking the link its not working?

**Comment by lantianlaoli** [comment]
![image](https://github.com/user-attachments/assets/6b68189a-d1de-4662-b247-7fe84844dfc9)
Check the VPN proxy settings, Isn't this website deployed by yourself?

**Comment by Anu27n** [comment]
@cxp-13  It shows the wbesite for 2 seconds then blank screen appears have checked the link in PC.Smartphone same issue coming again and again

**Comment by Anu27n** [comment]
@cxp-13 
<img width="418" alt="image" src="https://github.com/user-attachments/assets/96a9980f-9af4-40ec-a38b-d88aeee3bb2d" />

**Comment by lantianlaoli** [comment]
Could you check that the MetaMask plug is normally running on your browser? And check again whether the network is normal.

**Comment by Anu27n** [comment]
@cxp-13 does this require any meta-mask extension?

**Comment by Anu27n** [comment]
@cxp-13 oh it works now after installing the meta mask extension but is there any other way ?

**Comment by lantianlaoli** [comment]
> @cxp-13 oh it works now after installing the meta mask extension but is there any other way ?
Any wallet plugin is fine, such as Rainbow、OKX etc.

**Comment by Anu27n** [comment]
@cxp-13 hey do u know how to resolve this 
<img width="735" alt="image" src="https://github.com/user-attachments/assets/f55c5eb2-739d-475c-9d4c-bb178ddc9e80" />

**Comment by lantianlaoli** [comment]
> @cxp-13 hey do u know how to resolve this <img alt="image" width="735" src="https://private-user-images.githubusercontent.com/121352263/396792385-f55c5eb2-739d-475c-9d4c-bb178ddc9e80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MDU0NDEsIm5iZiI6MTczNDUwNTE0MSwicGF0aCI6Ii8xMjEzNTIyNjMvMzk2NzkyMzg1LWY1NWM1ZWIyLTczOWQtNDc1Yy05ZDRjLWJiMTc4ZGRjOWU4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQwNjU5MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZmE3ZWU3OGUwMWE4MWZkZTE5ZmM5ZTZkZGZkM2U4MmI2ZWEwZTI1MDMxMzQ2YWRmMzM0NzRjZjQxZTVmOTUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.15j75lv1BWBRD0TrJWfEfxJ70x3Y6ZbG4YIDzpzwSDY">

Feel free to ask GPT, I never touch it.
